export const REQUEST_ADD_COURSE = 'REQUEST_ADD_COURSE'
export const RECEIVE_ADD_COURSE = 'RECEIVE_ADD_COURSE'
export const REQUEST_TEACHER_COURSES_INFO = 'REQUEST_TEACHER_COURSES_INFO'
export const RECEIVE_TEACHER_COURSES_INFO = 'RECEIVE_TEACHER_COURSES_INFO'

// course state
export const SAVED = 'SAVED'
export const POSTED = 'POSTED'
export const CANCELED = 'CANCELED'
export const CLOSED = 'CLOSED'